spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Ex8CrudOperations
    username: root
    password: linda010495-pw
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
jackson:
  serialization:
    fail-on-empty-beans: false